version: "3.9"

services:

  backend:
    container_name: backend
    build: backend
    restart: "unless-stopped"
    networks:
      - backend
      - frontend
    env_file:
      - .env
    ports:
      - 4000:3000
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build: frontend
    restart: "unless-stopped"
    networks:
      - frontend
    ports:
      - 8081:80

  postgres:
    container_name: postgres
    image: "postgres:12"
    restart: "unless-stopped"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - backend


volumes:
  pgdata:

networks:
  frontend:
  backend:
